version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: aii
      MONGO_INITDB_ROOT_PASSWORD: aii
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  server:
    build:
      context: ./server  # Construir la imagen desde la carpeta 'server'
    container_name: server
    ports:
      - "3000:3000"  # Puerto para tu servidor Node.js
    env_file:
      - ./server/.env  # Cargar las variables de entorno desde el archivo .env dentro de 'server'
    depends_on:
      - mongodb  # El servidor depende de MongoDB para levantarse

 # Servicio del frontend (Angular)
  frontend:
    build:
      context: ./IoT
    container_name: frontend_IoT
    ports:
      - "80:80"  # Exponer el puerto 80
    depends_on:
      - server

volumes:
  mongodb_data:
  mongodb_config:
