services:
  mongodb-aura:
    image: mongo:latest
    container_name: mongodb-aura
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: aai
      MONGO_INITDB_ROOT_PASSWORD: aai
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - default

  mongo-fiware:
    image: mongo:6
    container_name: mongo-fiware
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - default

  # api-aura:
  #   build:
  #     context: ./api_aura 
  #   container_name: api_aura
  #   ports:
  #     - "8090:8090"
  #   env_file:
  #     - ./api_aura/.env 
  #   depends_on:
  #     - mongodb-aura
  #   networks:
  #     - default

  # aura:
  #   build:
  #     context: ./aura
  #   container_name: aura
  #   ports:
  #     - "4201:4201" 
  #   depends_on:
  #     - api-aura
  #   networks:
  #     - default

  orion:
    image: fiware/orion
    container_name: fiware-orion
    hostname: orion
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongo-fiware:27017
    depends_on:
      - mongo-fiware
    networks:
      - default

  fiware-iot-agent:
    image: fiware/iotagent-json:latest
    container_name: fiware-iot-agent
    restart: always
    depends_on:
      - mongo-fiware
      - orion
      - mosquitto
    ports:
      - "4041:4041"
      - "7896:7896"
    environment:
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_MONGO_HOST=mongo-fiware
      - IOTA_MONGO_PORT=27017
      - IOTA_MQTT_HOST=mosquitto
      - IOTA_MQTT_PORT=1883
      - IOTA_HTTP_PORT=7896
      - IOTA_PROVIDER_URL=http://fiware-iot-agent:4041
      - "IOTA_MONGO_DB=iotagentJson"

    networks:
      - default

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_log:/mosquitto/log
    networks:
      - default

  crate-db:
    image: crate
    container_name: crate-db
    hostname: crate-db
    ports:
      - "4200:4200"
      - "4300:4300"
      - "5432:5432"
    expose:
      - "4200"
    volumes:
      - crate-db:/data
    environment:
      - CRATE-HEAP-SIZE=4G
    networks:
      - default

  quantumleap:
    image: orchestracities/quantumleap
    container_name: quantumleap
    depends_on:
      - crate-db
      - orion
    ports:
      - "8668:8668"
    environment:
      - QL_LOGLEVEL=DEBUG
      - CRATE_HOST=crate-db
      - USE_GEOCODING=False
      - CACHE_QUERIES=False
    networks:
      - default

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - crate-db
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - default

volumes:
  mongodb_data:
  mongodb_config:
  mongo_data:
  mosquitto_data:
  mosquitto_config:
  mosquitto_log:
  crate-db:
  grafana:

networks:
  default:
    ipam:
      config:
        - subnet: 10.0.0.0/24
